"""GitRisk rule database."""

from dataclasses import dataclass
from typing import Dict, List

@dataclass
class RuleDoc:
    rule_id: str
    title: str
    category: str
    severity: str
    cwe: List[str]
    owasp: List[str]
    description: str
    impact: str
    remediation: List[str]
    examples: Dict[str, str]
    references: List[str]
    tags: List[str]

RULES: Dict[str, RuleDoc] = {
    "SEC-001": RuleDoc(
        rule_id="SEC-001",
        title="AWS Access Key ID",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found AWS Access Key ID. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-001 = 'secret'", "good": "SEC-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-002": RuleDoc(
        rule_id="SEC-002",
        title="AWS Secret Access Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found AWS Secret Access Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-002 = 'secret'", "good": "SEC-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-003": RuleDoc(
        rule_id="SEC-003",
        title="GitHub Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-522"],
        owasp=["A07:2021"],
        description="Found GitHub Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-003 = 'secret'", "good": "SEC-003 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-004": RuleDoc(
        rule_id="SEC-004",
        title="GitHub Fine-Grained Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-522"],
        owasp=["A07:2021"],
        description="Found GitHub Fine-Grained Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-004 = 'secret'", "good": "SEC-004 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-005": RuleDoc(
        rule_id="SEC-005",
        title="Slack Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-522"],
        owasp=["A07:2021"],
        description="Found Slack Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-005 = 'secret'", "good": "SEC-005 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-006": RuleDoc(
        rule_id="SEC-006",
        title="Stripe Secret Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Stripe Secret Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-006 = 'secret'", "good": "SEC-006 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-007": RuleDoc(
        rule_id="SEC-007",
        title="SendGrid API Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found SendGrid API Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-007 = 'secret'", "good": "SEC-007 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-008": RuleDoc(
        rule_id="SEC-008",
        title="Google API Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Google API Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-008 = 'secret'", "good": "SEC-008 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-009": RuleDoc(
        rule_id="SEC-009",
        title="Twilio Auth Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Twilio Auth Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-009 = 'secret'", "good": "SEC-009 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-010": RuleDoc(
        rule_id="SEC-010",
        title="RSA Private Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-321"],
        owasp=["A07:2021"],
        description="Found RSA Private Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-010 = 'secret'", "good": "SEC-010 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-011": RuleDoc(
        rule_id="SEC-011",
        title="OpenSSH Private Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-321"],
        owasp=["A07:2021"],
        description="Found OpenSSH Private Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-011 = 'secret'", "good": "SEC-011 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-012": RuleDoc(
        rule_id="SEC-012",
        title="Generic PEM Private Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-321"],
        owasp=["A07:2021"],
        description="Found Generic PEM Private Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-012 = 'secret'", "good": "SEC-012 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-013": RuleDoc(
        rule_id="SEC-013",
        title="NPM Auth Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-522"],
        owasp=["A07:2021"],
        description="Found NPM Auth Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-013 = 'secret'", "good": "SEC-013 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-014": RuleDoc(
        rule_id="SEC-014",
        title="Mailchimp API Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Mailchimp API Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-014 = 'secret'", "good": "SEC-014 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-015": RuleDoc(
        rule_id="SEC-015",
        title="Mailgun API Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Mailgun API Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-015 = 'secret'", "good": "SEC-015 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-016": RuleDoc(
        rule_id="SEC-016",
        title="Telegram Bot Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Telegram Bot Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-016 = 'secret'", "good": "SEC-016 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-017": RuleDoc(
        rule_id="SEC-017",
        title="Heroku API Key",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Heroku API Key. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-017 = 'secret'", "good": "SEC-017 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-018": RuleDoc(
        rule_id="SEC-018",
        title="PyPI Token",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found PyPI Token. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-018 = 'secret'", "good": "SEC-018 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-019": RuleDoc(
        rule_id="SEC-019",
        title="Basic Auth in URL",
        category="Secrets",
        severity="CRITICAL",
        cwe=["CWE-522"],
        owasp=["A07:2021"],
        description="Found Basic Auth in URL. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-019 = 'secret'", "good": "SEC-019 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "SEC-020": RuleDoc(
        rule_id="SEC-020",
        title="Generic Secret Assignment",
        category="Secrets",
        severity="HIGH",
        cwe=["CWE-798"],
        owasp=["A07:2021"],
        description="Found Generic Secret Assignment. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "SEC-020 = 'secret'", "good": "SEC-020 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["secrets", "security"]
    ),
    "DEP-001": RuleDoc(
        rule_id="DEP-001",
        title="Vulnerable dependency",
        category="Dependencies",
        severity="HIGH",
        cwe=["CWE-937"],
        owasp=["A06:2021"],
        description="Found Vulnerable dependency. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "DEP-001 = 'secret'", "good": "DEP-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["dependencies", "security"]
    ),
    "DEP-002": RuleDoc(
        rule_id="DEP-002",
        title="Vulnerable dependency (requests)",
        category="Dependencies",
        severity="HIGH",
        cwe=["CWE-937"],
        owasp=["A06:2021"],
        description="Found Vulnerable dependency (requests). This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "DEP-002 = 'secret'", "good": "DEP-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["dependencies", "security"]
    ),
    "DEP-003": RuleDoc(
        rule_id="DEP-003",
        title="Vulnerable dependency (pytest)",
        category="Dependencies",
        severity="HIGH",
        cwe=["CWE-937"],
        owasp=["A06:2021"],
        description="Found Vulnerable dependency (pytest). This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "DEP-003 = 'secret'", "good": "DEP-003 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["dependencies", "security"]
    ),
    "ENV-001": RuleDoc(
        rule_id="ENV-001",
        title=".env file tracked by Git",
        category="Environment",
        severity="CRITICAL",
        cwe=["CWE-200"],
        owasp=["A02:2021"],
        description="Found .env file tracked by Git. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "ENV-001 = 'secret'", "good": "ENV-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["environment", "security"]
    ),
    "GHA-001": RuleDoc(
        rule_id="GHA-001",
        title="Workflow permissions not restricted",
        category="GitHub Actions",
        severity="MEDIUM",
        cwe=["CWE-250"],
        owasp=[],
        description="Found Workflow permissions not restricted. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GHA-001 = 'secret'", "good": "GHA-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["github actions", "security"]
    ),
    "GHA-002": RuleDoc(
        rule_id="GHA-002",
        title="Elevated write permission in workflow",
        category="GitHub Actions",
        severity="HIGH",
        cwe=["CWE-250"],
        owasp=["A01:2021"],
        description="Found Elevated write permission in workflow. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GHA-002 = 'secret'", "good": "GHA-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["github actions", "security"]
    ),
    "GHA-003": RuleDoc(
        rule_id="GHA-003",
        title="Use of pull_request_target trigger",
        category="GitHub Actions",
        severity="HIGH",
        cwe=["CWE-250"],
        owasp=[],
        description="Found Use of pull_request_target trigger. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GHA-003 = 'secret'", "good": "GHA-003 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["github actions", "security"]
    ),
    "GIT-001": RuleDoc(
        rule_id="GIT-001",
        title="Large binary file committed",
        category="Git Configuration",
        severity="MEDIUM",
        cwe=["CWE-400"],
        owasp=[],
        description="Found Large binary file committed. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-001 = 'secret'", "good": "GIT-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-002": RuleDoc(
        rule_id="GIT-002",
        title=".gitignore missing critical security patterns",
        category="Git Configuration",
        severity="HIGH",
        cwe=["CWE-200"],
        owasp=[],
        description="Found .gitignore missing critical security patterns. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-002 = 'secret'", "good": "GIT-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-010": RuleDoc(
        rule_id="GIT-010",
        title="Not a Git repository",
        category="Git Configuration",
        severity="INFO",
        cwe=[],
        owasp=[],
        description="Found Not a Git repository. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-010 = 'secret'", "good": "GIT-010 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-011": RuleDoc(
        rule_id="GIT-011",
        title="fileMode disabled",
        category="Git Configuration",
        severity="INFO",
        cwe=[],
        owasp=[],
        description="Found fileMode disabled. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-011 = 'secret'", "good": "GIT-011 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-012": RuleDoc(
        rule_id="GIT-012",
        title="Shared repository mode enabled",
        category="Git Configuration",
        severity="MEDIUM",
        cwe=["CWE-284"],
        owasp=[],
        description="Found Shared repository mode enabled. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-012 = 'secret'", "good": "GIT-012 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-013": RuleDoc(
        rule_id="GIT-013",
        title="SSL verification disabled",
        category="Git Configuration",
        severity="HIGH",
        cwe=["CWE-295"],
        owasp=[],
        description="Found SSL verification disabled. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-013 = 'secret'", "good": "GIT-013 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "GIT-014": RuleDoc(
        rule_id="GIT-014",
        title="Git credential helper stores plaintext",
        category="Git Configuration",
        severity="HIGH",
        cwe=["CWE-522"],
        owasp=[],
        description="Found Git credential helper stores plaintext. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "GIT-014 = 'secret'", "good": "GIT-014 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["git configuration", "security"]
    ),
    "HRD-001": RuleDoc(
        rule_id="HRD-001",
        title="Hardcoded database connection string",
        category="Hardcoding",
        severity="CRITICAL",
        cwe=["CWE-259"],
        owasp=["A02:2021"],
        description="Found Hardcoded database connection string. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-001 = 'secret'", "good": "HRD-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "HRD-002": RuleDoc(
        rule_id="HRD-002",
        title="Hardcoded password",
        category="Hardcoding",
        severity="CRITICAL",
        cwe=["CWE-259"],
        owasp=["A07:2021"],
        description="Found Hardcoded password. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-002 = 'secret'", "good": "HRD-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "HRD-003": RuleDoc(
        rule_id="HRD-003",
        title="Hardcoded private IP address",
        category="Hardcoding",
        severity="MEDIUM",
        cwe=["CWE-200"],
        owasp=[],
        description="Found Hardcoded private IP address. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-003 = 'secret'", "good": "HRD-003 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "HRD-004": RuleDoc(
        rule_id="HRD-004",
        title="Hardcoded internal IP address",
        category="Hardcoding",
        severity="MEDIUM",
        cwe=["CWE-200"],
        owasp=[],
        description="Found Hardcoded internal IP address. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-004 = 'secret'", "good": "HRD-004 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "HRD-005": RuleDoc(
        rule_id="HRD-005",
        title="Hardcoded port number",
        category="Hardcoding",
        severity="LOW",
        cwe=["CWE-200"],
        owasp=[],
        description="Found Hardcoded port number. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-005 = 'secret'", "good": "HRD-005 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "HRD-006": RuleDoc(
        rule_id="HRD-006",
        title="Hardcoded service endpoint",
        category="Hardcoding",
        severity="LOW",
        cwe=["CWE-200"],
        owasp=[],
        description="Found Hardcoded service endpoint. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "HRD-006 = 'secret'", "good": "HRD-006 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["hardcoding", "security"]
    ),
    "POL-001": RuleDoc(
        rule_id="POL-001",
        title="No SECURITY.md found",
        category="Policy",
        severity="LOW",
        cwe=[],
        owasp=[],
        description="Found No SECURITY.md found. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "POL-001 = 'secret'", "good": "POL-001 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["policy", "security"]
    ),
    "POL-002": RuleDoc(
        rule_id="POL-002",
        title="No README.md found",
        category="Policy",
        severity="INFO",
        cwe=[],
        owasp=[],
        description="Found No README.md found. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "POL-002 = 'secret'", "good": "POL-002 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["policy", "security"]
    ),
    "POL-003": RuleDoc(
        rule_id="POL-003",
        title="No CONTRIBUTING.md found",
        category="Policy",
        severity="INFO",
        cwe=[],
        owasp=[],
        description="Found No CONTRIBUTING.md found. This exposes sensitive information or configurations.",
        impact="Could lead to unauthorized access, data breach, or service disruption.",
        remediation=["Remove the hardcoded secret or configuration.", "Use environment variables or a secret manager.", "Rotate compromised credentials immediately."],
        examples={"bad": "POL-003 = 'secret'", "good": "POL-003 = os.getenv('SECRET')"},
        references=["https://cwe.mitre.org/", "https://owasp.org/"],
        tags=["policy", "security"]
    ),
}
